project:
  type: website
  output-dir: docs
website:
  title: "Jordan Spencer's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: research
      - href: ChatgptIntegration.qmd
        text: ChatGPT Integration
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

